# Generated by Django 4.2.23 on 2025-07-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drops', '0002_alter_drop_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropproduct',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5, help_text='Threshold for low stock alerts'),
        ),
        migrations.AddField(
            model_name='dropproduct',
            name='reserved_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Stock reserved for unpaid orders'),
        ),
        migrations.AddConstraint(
            model_name='dropproduct',
            constraint=models.CheckConstraint(check=models.Q(('reserved_quantity__gte', 0)), name='check_drop_reserved_quantity_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='dropproduct',
            constraint=models.CheckConstraint(check=models.Q(('reserved_quantity__lte', models.F('current_stock_quantity'))), name='check_drop_reserved_lte_current'),
        ),
    ]
