# Generated by Django 4.2.23 on 2025-07-11 15:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productvariant_low_stock_threshold_and_more'),
        ('drops', '0003_dropproduct_low_stock_threshold_and_more'),
        ('orders', '0006_alter_orderitem_product_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryReservation',
            fields=[
                ('reservation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reservation_type', models.CharField(choices=[('product_variant', 'Product Variant'), ('drop_product', 'Drop Product')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('drop_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='drops.dropproduct')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='orders.order')),
                ('product_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='products.productvariant')),
            ],
            options={
                'indexes': [models.Index(fields=['expires_at', 'is_active'], name='orders_inve_expires_01ce66_idx'), models.Index(fields=['order', 'is_active'], name='orders_inve_order_i_34ea9e_idx'), models.Index(fields=['product_variant', 'is_active'], name='orders_inve_product_8cbfac_idx'), models.Index(fields=['drop_product', 'is_active'], name='orders_inve_drop_pr_149e41_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='inventoryreservation',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='check_reservation_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='inventoryreservation',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('drop_product__isnull', False), ('product_variant__isnull', True)), models.Q(('drop_product__isnull', True), ('product_variant__isnull', False)), _connector='OR'), name='check_reservation_single_product_type'),
        ),
    ]
