# Generated by Django 4.2.23 on 2025-06-18 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_producttranslation_categorytranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytranslation',
            name='language_code',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('ar', 'العربية'), ('tr', 'Türkçe')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='language_code',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('ar', 'العربية'), ('tr', 'Türkçe')], db_index=True, max_length=10),
        ),
    ]
