# Generated by Django 4.2.23 on 2025-07-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_categorytranslation_language_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5, help_text='Threshold for low stock alerts'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='reserved_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Stock reserved for unpaid orders'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Total available stock'),
        ),
        migrations.AlterField(
            model_name='categorytranslation',
            name='language_code',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('ar', 'العربية'), ('tr', 'Türkçe'), ('zh', '中文')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='language_code',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('ar', 'العربية'), ('tr', 'Türkçe'), ('zh', '中文')], db_index=True, max_length=10),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['stock_quantity', 'reserved_quantity'], name='products_pr_stock_q_78c48d_idx'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(check=models.Q(('stock_quantity__gte', 0)), name='check_stock_quantity_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(check=models.Q(('reserved_quantity__gte', 0)), name='check_reserved_quantity_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(check=models.Q(('reserved_quantity__lte', models.F('stock_quantity'))), name='check_reserved_lte_stock'),
        ),
    ]
