# Generated by Django 4.2.23 on 2025-06-18 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text="Language code (e.g., 'en', 'ru', 'ar')", max_length=10, unique=True)),
                ('name', models.CharField(help_text="Language name in English (e.g., 'English', 'Russian')", max_length=100)),
                ('native_name', models.CharField(help_text="Language name in its native form (e.g., 'English', 'Русский')", max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this language is active and available for users')),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default language')),
                ('is_rtl', models.BooleanField(default=False, help_text='Whether this language is written right-to-left')),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Order in which to display this language in the switcher')),
                ('flag_code', models.CharField(blank=True, help_text="Two-letter country code for the flag (e.g., 'us', 'ru')", max_length=2, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
